device: cuda
seed: 425
total_timesteps: 100000000

app:
  headless: true
  enable_cameras: false

video:
  enabled: false
  interval: 10000
  length: 500

viewer:
  override: true
  resolution: [1080, 1080]
  eye_scale_factor: 2.0


