
env: ${experiment.env}
algo: ${experiment.algo}
model: ${experiment.model}
# --- 全局变量 ---
seed: 42
total_steps: 100_000_000
device: "cuda:0"
headless: True
livestream: 2
num_envs: 1

record_video: True
video_interval: 10000
video_length: 100

# --- Hydra 配置 ---
hydra:
  run:
    dir: outputs/${env.name}/${experiment.name}/${model.name}_${now:%Y%m%d_%H%M}
  job:
      chdir: True
  verbose: []
defaults:
  - experiment: debug
  - _self_                # 4. 【【关键】】加载本文件中的所有其他键
