learning_rate: 4e-5
n_steps: 128
mini_batches: 32
n_epochs: 4
gamma: 0.99
ent_coef: 0.01
clip_range: 0.1
value_loss_scale: 0.5
kl_threshold: 0.0

normalization:
  norm_obs: false
  norm_reward: true

experiment:
  write_interval: 1
  checkpoint_interval: 100000


